package com.vachana.qa.steps.ui;

import com.vachana.qa.context.TestContext;
import com.vachana.qa.models.Customer;
import com.vachana.qa.pages.CategoryPage;
import com.vachana.qa.pages.ContactUsPage;
import com.vachana.qa.pages.HomePage;
import com.vachana.qa.utils.RandomDataUtils;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import org.testng.Assert;

import java.nio.file.Path;

public class ContactSubscriptionCategorySteps {
    @When("I open the Contact Us page")
    public void iOpenTheContactUsPage() {
        new HomePage().goToContactUs();
    }

    @When("I submit the contact us form with test data")
    public void iSubmitTheContactUsFormWithTestData() {
        Customer customer = TestContext.find("customer", Customer.class).orElseGet(RandomDataUtils::uniqueCustomer);
        new ContactUsPage().submitMessage(
                customer,
                "Automation feedback",
                "This is a fake test message generated by the automation framework.",
                Path.of("src/test/resources/testdata/contact_upload.txt")
        );
    }

    @Then("the contact success message should be visible")
    public void theContactSuccessMessageShouldBeVisible() {
        Assert.assertTrue(new ContactUsPage().successVisible(), "Contact success message should be visible");
    }

    @When("I subscribe with a unique email from the footer")
    public void iSubscribeWithAUniqueEmailFromTheFooter() {
        new HomePage().subscribeWith(RandomDataUtils.uniqueEmail());
    }

    @Then("the subscription success message should be visible")
    public void theSubscriptionSuccessMessageShouldBeVisible() {
        Assert.assertTrue(new HomePage().subscriptionSuccessVisible(), "Subscription success should be visible");
    }

    @When("I open {string} category {string}")
    public void iOpenCategory(String parentCategory, String childCategory) {
        new CategoryPage().openCategory(parentCategory, childCategory);
    }

    @Then("the category products heading should contain {string}")
    public void theCategoryProductsHeadingShouldContain(String expectedHeading) {
        Assert.assertTrue(new CategoryPage().headingContains(expectedHeading), "Category products heading should contain expected category");
    }

    @When("I move the home carousel to the next banner")
    public void iMoveTheHomeCarouselToTheNextBanner() {
        HomePage homePage = new HomePage();
        int beforeIndex = homePage.activeCarouselIndex();
        int afterIndex = homePage.moveToNextCarouselBanner();
        TestContext.put("carouselBefore", beforeIndex);
        TestContext.put("carouselAfter", afterIndex);
    }

    @Then("the home carousel banner should change")
    public void theHomeCarouselBannerShouldChange() {
        int beforeIndex = TestContext.get("carouselBefore", Integer.class);
        int afterIndex = TestContext.get("carouselAfter", Integer.class);
        Assert.assertNotEquals(afterIndex, beforeIndex, "Carousel should move to a different banner");
    }

    @When("I move the home carousel to the previous banner")
    public void iMoveTheHomeCarouselToThePreviousBanner() {
        HomePage homePage = new HomePage();
        int beforeIndex = homePage.activeCarouselIndex();
        int afterIndex = homePage.moveToPreviousCarouselBanner();
        TestContext.put("carouselPreviousBefore", beforeIndex);
        TestContext.put("carouselPreviousAfter", afterIndex);
    }

    @Then("the home carousel banner should change again")
    public void theHomeCarouselBannerShouldChangeAgain() {
        int beforeIndex = TestContext.get("carouselPreviousBefore", Integer.class);
        int afterIndex = TestContext.get("carouselPreviousAfter", Integer.class);
        Assert.assertNotEquals(afterIndex, beforeIndex, "Carousel should move back to a different banner");
    }

    @When("I scroll down to the footer")
    public void iScrollDownToTheFooter() {
        new HomePage().scrollToFooter();
    }

    @Then("the subscription section should be visible")
    public void theSubscriptionSectionShouldBeVisible() {
        Assert.assertTrue(new HomePage().subscriptionSectionVisible(), "Subscription section should be visible");
    }

    @When("I click the scroll up arrow")
    public void iClickTheScrollUpArrow() {
        new HomePage().clickScrollUpArrow();
    }

    @When("I scroll up to the top without using the arrow")
    public void iScrollUpToTheTopWithoutUsingTheArrow() {
        new HomePage().scrollToTopWithoutArrow();
    }

    @Then("the home page hero text should be visible")
    public void theHomePageHeroTextShouldBeVisible() {
        Assert.assertTrue(new HomePage().heroTextVisible(), "Home page hero text should be visible");
    }
}
